export const movies = [
    "Home Alone",
    "Home Alone 2",
    "home alone 3",
    "National Lampoon Christmas",
    "i'll be home for christmas",
    "frosty the snowman",
    "santa claus is coming to town",
    "the year without a santa claus",
    "Jack Frost (clay)",
    "jack frost (michael keaton)",
    "Rudolph the red nosed reigndeer",
    "rudolphs shiny new year",
    "it's a wonderful life",
    "The santa claus",
    "the santa claus 2",
    "the santa claus 3",
    "the santa clauses",
    "violent night",
    "a christmas story",
    "a christmas story 2",
    "the grinch (jim carey)",
    "the grinch (animated)",
    "polar express",
    "a christmas carol",
    "Christmas with the kranks",
    "jingle all the way",
    "klaus",
    "christmas chronicles",
    "christmas chronicles 2",
    "noelle",
    "prancer",
    "deck the halls",
    "unaccompanied minors",
    "last holiday",
    "fred claus",
    "arthur christmas",
    "muppet christmas carol",
    "richy rich christmas wish",
    "nutcracker and the four realms",
    "nutcracker",
    "babes in toyland",
    "jingle jangle",
    "the snowman (short)",
    "the family man",
    "just friends",
    "last christmas",
    "scrooged",
    "all i want for christmas",
    "die hard",
    "miracle on 34th street",
    "the boy named christmas",
    "a castle for christmas",
    "8-bit christmas",
    "home sweet home alone",
    "single all the way",
    "the knight before christmas",
];
